In [11]:
import pandas as pd
from ydata_profiling import ProfileReport

# 1. Importing the datasets

In [21]:
feargreed = pd.read_csv("fg_index.csv")

In [3]:
history = pd.read_csv("hist_data.csv")

# 2. Cleaning the Data

In [21]:
feargreed.shape

(2644, 4)

In [11]:
feargreed.head(5)

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [22]:
history.shape

(211224, 16)

In [12]:
history.head(5)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [9]:
feargreed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            2644 non-null   object
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
dtypes: int64(1), object(2)
memory usage: 62.1+ KB

In [6]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

### Optimising the DATA

In [22]:
feargreed = feargreed.drop(columns=["timestamp"])
feargreed = feargreed[["date", "value", "classification"]]

In [23]:
feargreed.head(3)

         date  value classification
0  2018-02-01     30           Fear
1  2018-02-02     15   Extreme Fear
2  2018-02-03     40           Fear

In [44]:
history = history.drop(columns=["Timestamp"])

In [48]:
history['Timestamp IST'] = pd.to_datetime(history['Timestamp IST'], format='%d-%m-%Y %H:%M')

In [50]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  datetime64[ns]
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 22.8+ MB

In [4]:
profile = ProfileReport(history, title="History Dataset Profiling Report", explorative=True)
profile.to_file("output_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]
  6%|▋         | 1/16 [00:01<00:13,  1.10it/s]
 12%|█▎        | 2/16 [00:01<00:08,  1.59it/s]
 19%|█▉        | 3/16 [00:02<00:07,  1.77it/s]
 25%|██▌       | 4/16 [00:02<00:08,  1.46it/s]
 31%|███▏      | 5/16 [00:03<00:06,  1.58it/s]
 38%|███▊      | 6/16 [00:03<00:04,  2.12it/s]
100%|██████████| 16/16 [00:09<00:00,  1.65it/s][A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [41]:
feargreed['date'] = pd.to_datetime(feargreed['date'])

In [42]:
feargreed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            2644 non-null   datetime64[ns]
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 62.1+ KB

In [43]:
feargreed.head(3)

        date  value classification
0 2018-02-01     30           Fear
1 2018-02-02     15   Extreme Fear
2 2018-02-03     40           Fear

In [51]:
feargreed.to_csv("fear_greed.csv", index=False)

In [52]:
history.to_csv("history_data.csv", index=False)

In [58]:
from sqlalchemy import create_engine
import pymysql

In [62]:
engine = create_engine("mysql+pymysql://root:password@localhost:3306/trade")
feargreed.to_sql(
    name='fear_greed',
    con=engine,
    if_exists='replace',
    index=False
)
print("done!")

done!

In [61]:
engine = create_engine("mysql+pymysql://root:password@localhost:3306/trade")
history.to_sql(
    name='history_data',
    con=engine,
    if_exists='replace',
    index=False
)
print("done!")

done!